-- TEXT_AETHERGAZER_EXPANSION_VIII
-- Author: HK433
-- DateCreated: 12/30/2023 9:39:26 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES

--陵光外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','有事，知会我便是'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','不可'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','你的体质,我先前从没有见过。如果可以的话，我希望能再仔细为你检查一番'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','承蒙关照，我也定会以自己的方式回报'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','嗯，也罢'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','扇中之火，亦可燎原'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','我便送你一程！'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','我已将你派来的使者安顿好，尽可放心'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','今日公事繁忙，恕不接待'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','我做了些糕点,希望能合你口味'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','飘风不终朝，骤雨不终日'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','若与苍生为敌，则无药可救'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','你好，陌生人，看你的样子应该不是本地人，是为探病求医而来嘛？'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','欢迎你来到虚恒，不介意的话，请随我一同游览'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','嗯，我接受你的邀请'),
--遇见人类，互相交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','你愿意在地图上标注一下你的城市嘛？作为交换，我也会告诉你虚恒的位置'),
--请求结盟，没用过
-- ('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','天下邪祟无处不在，凭乌一人之力，恐难将其悉数歼灭，随乌一行侠仗义，还天下太平！'),
--警告玩家边境部队太多
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','耀武扬威，终将自生自灭'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','希望你的承诺能够兑现'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','苍茫大地，为何在这儿偏安一隅？'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','鼠目寸光之人'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','我知道你对四方院有大的好奇心，但了解我们不应该采取这样的手段'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','放肆！'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','己所不欲，勿施于人'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','你会自食其果'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','气运无常....'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_NEUTRAL','zh_Hans_CN','多谢'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_HAPPY','zh_Hans_CN','多谢'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_UNHAPPY','zh_Hans_CN','多谢'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_NEUTRAL','zh_Hans_CN','无妨'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_HAPPY','zh_Hans_CN','无妨'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_LINGGUANG_AETHERGAZER_UNHAPPY','zh_Hans_CN','无妨'),
--议程好感
-- ('LOC_DIPLO_KUDO_EXIT_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN',''),
--议程厌恶
('LOC_DIPLO_WARNING_EXIT_LEADER_LINGGUANG_AETHERGAZER_ANY','zh_Hans_CN','不见苍生,不知苦处。我既见苍生、既知其苦，也就再难对此坐视不理（你拥有太多宜居度不足的城市）'),
--议程好感显示
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_LINGGUANG_HAPPY','zh_Hans_CN',''),
--议程厌恶显示，没有
('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_LINGGUANG_SAD','zh_Hans_CN','陵光对你辜负市民的期望感到愤怒'),

('LOC_CIVILIZATION_AETHERGAZER_GREY_LINGGUANG_NAME','zh_Hans_CN','天垣神域-澄心'),
('LOC_CIVILIZATION_AETHERGAZER_GREY_LINGGUANG_CAPITALNAME','zh_Hans_CN','神域·天垣'),
--领袖名字
('LOC_LEADER_LINGGUANG_AETHERGAZER_NAME','zh_Hans_CN','陵光'),
--陵光
('LOC_PEDIA_LEADERS_PAGE_LEADER_LINGGUANG_AETHERGAZER_QUOTE','zh_Hans_CN','尘归尘，土归土'),
('LOC_TRAIT_LEADER_LINGGUANG_AETHERGAZER_NAME','zh_Hans_CN','天南法门'),
('LOC_TRAIT_LEADER_LINGGUANG_AETHERGAZER_DESCRIPTION','zh_Hans_CN','创建首都后，立即获得金乌和陵光，所有城市永久忠诚，单位无需驻扎在回合开始时恢复生命。{LOC_HAPPINESS_CONTENT_NAME}的城市+10%[ICON_Production][ICON_Gold][ICON_Faith][ICON_Culture][ICON_Science]非食物产出，{LOC_HAPPINESS_HAPPY_NAME}、{LOC_HAPPINESS_ECSTATIC_NAME}的城市+10%[ICON_Production][ICON_Gold][ICON_Faith][ICON_Culture][ICON_Science]非食物产出，[ICON_Science]科技值和[ICON_Culture]文化值额外+10%，{LOC_HAPPINESS_DISPLEASED_NAME}、{LOC_HAPPINESS_UNHAPPY_NAME}、{LOC_HAPPINESS_UNREST_NAME}、{LOC_HAPPINESS_REVOLT_NAME}的城市-25%[ICON_Production][ICON_Gold][ICON_Faith][ICON_Culture][ICON_Science]非食物产出，四方院+1[ICON_Amenities]宜居度，神社和市场+3[ICON_Amenities]宜居度，由您创建的非首都城市+2[ICON_Amenities]宜居度。'),
('LOC_LOADING_INFO_LEADER_LINGGUANG_AETHERGAZER','zh_Hans_CN','我自然知道这人海茫茫,苦无尽时。然而圣人之术，可为万民式,我所做的还远远不够——陵光'),
('LOC_AGENDA_LINGGUANG_NAME','zh_Hans_CN','医者仁心'),
('LOC_AGENDA_LINGGUANG_DESCRIPTION','zh_Hans_CN','讨厌拥有大量宜居度不足城市的文明');

