-- TEXT_AETHERGAZER_EXPANSION_PART_GENCHEN
-- Author: HK433
-- DateCreated: 7/4/2024 5:15:03 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
--庚辰外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','我同意这份友谊'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','取舍并非易事，但眼下拒绝是最好的选择'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','你我愿景相似，志同道合，不是么？'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','今后遇到什么困难，尽管对我说'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','也好'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','战斗，没有一日宁息吗？'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','无为，无不为'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','我已经安顿好你的使者了，请放心'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','恕我直言，现在四方院还有更重要的事情要做，没有时间处理这些问题'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','这是我从虚恒带来的一些茶叶、器皿以及一些时令蔬菜，希望你能够接纳'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','无用功'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','我不会阻止你去做什么，但你最近的行为令人憎恨'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','四方院，庚辰，有什么事嘛？'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','请随我来，虚恒有很多地方值得欣赏'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','嗯，感谢你的邀请'),
--遇见人类，互相交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','如果你不嫌弃，还请你在地图上标注你们的位置吧，我也会告诉你我们的位置'),
--请求结盟
-- ('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN',''),
--警告玩家边境部队太多
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','乌合之众，休得猖狂'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','若无此意，请速速退兵'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','你的扩张行为是否可以收敛一下'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','无话可说'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','若对四方院感兴趣，为何不感直面我？'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','小人行径'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','我们拥有自己的信仰，请你的信徒不要再来打扰了'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','那就顺其自然'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','此身使命，远未完成....'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_GENCHEN_AETHERGAZER_NEUTRAL','zh_Hans_CN','嗯，谢谢合作'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_GENCHEN_AETHERGAZER_HAPPY','zh_Hans_CN','嗯，谢谢合作'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_GENCHEN_AETHERGAZER_UNHAPPY','zh_Hans_CN','嗯，谢谢合作'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_GENCHEN_AETHERGAZER_NEUTRAL','zh_Hans_CN','无妨'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_GENCHEN_AETHERGAZER_HAPPY','zh_Hans_CN','无妨'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_GENCHEN_AETHERGAZER_UNHAPPY','zh_Hans_CN','无妨'),
--议程好感
-- ('LOC_DIPLO_KUDO_EXIT_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','感谢您对天禄贸易的信任'),
--议程厌恶
('LOC_DIPLO_WARNING_EXIT_LEADER_GENCHEN_AETHERGAZER_ANY','zh_Hans_CN','如果你的人民没有财富，再伟大的建筑也掩盖不住颓势'),
--议程好感显示
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_GENCHEN_HAPPY','zh_Hans_CN','英招喜欢宣布友好的文明'),
--议程厌恶显示
('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_GENCHEN_SAD','zh_Hans_CN','庚辰讨厌你城市里数量众多的奇观'),
--文明名字
('LOC_CIVILIZATION_AETHERGAZER_GREY_GENCHEN_NAME','zh_Hans_CN','天垣神域-太一'),
('LOC_CIVILIZATION_AETHERGAZER_GREY_GENCHEN_CAPITALNAME','zh_Hans_CN','神域·天垣'),
--领袖名字
('LOC_LEADER_GENCHEN_AETHERGAZER_NAME','zh_Hans_CN','庚辰'),
--英招
('LOC_PEDIA_LEADERS_PAGE_LEADER_GENCHEN_AETHERGAZER_QUOTE','zh_Hans_CN','如果遇到什么困难，尽管对我说'),
('LOC_TRAIT_LEADER_GENCHEN_AETHERGAZER_NAME','zh_Hans_CN','大荒流泽'),
('LOC_TRAIT_LEADER_GENCHEN_AETHERGAZER_DESCRIPTION','zh_Hans_CN','创建首都后立即获得执明、庚辰，你的文明每进入一个新时代，建造原质区地标区域内的建筑+5%[ICON_Production]生产力。未拥有原质区地标区域时，所有城市+3[ICON_Faith]信仰。拥有原质区地标区域时，但没有同一时代所有地标建筑时，建造者购买[ICON_Gold]费用-33%。拥有所有{LOC_ERA_CLASSICAL_NAME}地标建筑，但没有更高时代的所有地标建筑时，所有城市+100%[ICON_Gold]金币。拥有所有{LOC_ERA_RENAISSANCE_NAME}地标建筑，但没有更高时代的所有地标建筑时，您的城市现在可以生产重装近战修正者，所有城市+35%[ICON_Production]生产力。拥有所有{LOC_ERA_MODERN_NAME}地标建筑，所有城市+30%[ICON_Science]科技值'),
('LOC_LOADING_INFO_LEADER_GENCHEN_AETHERGAZER','zh_Hans_CN','岁月不会改变我们的本质。无论能力高下，见识多寡，我们总是在探寻万事万物存在的意义......我们此时认可的答案，恐怕仍是海面冰山。——庚辰'),
('LOC_AGENDA_GENCHEN_NAME','zh_Hans_CN','实用主义'),
('LOC_AGENDA_GENCHEN_DESCRIPTION','zh_Hans_CN','讨厌奇观太多的文明');


--+2[ICON_Food]粮食+2[ICON_Production]生产力+2[ICON_Faith]信仰