-- TEXT_AETHERGAZER_EXPANSION_IV
-- Author: HK433
-- DateCreated: 8/15/2023 10:11:41 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
--托尔
('LOC_CIVILIZATION_AETHERGAZER_GREEN_HAIMUDAER_NAME','zh_Hans_CN','圣树神域♩♪'),
('LOC_CIVILIZATION_AETHERGAZER_GREEN_HAIMUDAER_CAPITALNAME','zh_Hans_CN','神域·圣树'),
--领袖名字
('LOC_LEADER_HAIMUDAER_AETHERGAZER_NAME','zh_Hans_CN','海姆达尔'),
--海姆达尔
('LOC_PEDIA_LEADERS_PAGE_LEADER_HAIMUDAER_AETHERGAZER_QUOTE','zh_Hans_CN','我始终觉得只有用万全的理论作为基石,才能做出完美的研究成果。比起追求结果,我更喜欢推导理论的过程。'),
('LOC_TRAIT_LEADER_HAIMUDAER_AETHERGAZER_NAME','zh_Hans_CN','极境神域'),
('LOC_TRAIT_LEADER_HAIMUDAER_AETHERGAZER_DESCRIPTION','zh_Hans_CN','创建首都后，立即获得大国主、海姆达尔，循理之环无需初始的高额[ICON_Gold]维护费且训练该单位时+100%[ICON_Production]生产力。建造学院和工业区区域时+500%[ICON_Production]生产力，建成后会获得一个区域位。战斗胜利后，获得等同于被击杀单位[ICON_Strength]战斗力200%的[ICON_Gold]金币和[ICON_Science]科技值（标准速度下）。可更早组建军团（需法典市政）且城市无需军事学院，可直接训练军团和军队。军团和军队的训练费用降低10%'),
('LOC_LOADING_INFO_LEADER_HAIMUDAER_AETHERGAZER','zh_Hans_CN','那个理论派，大概是不会知道实践的乐趣了...——大国主'),
('LOC_AGENDA_HAIMUDAER_NAME','zh_Hans_CN','笃信科学'),
('LOC_AGENDA_HAIMUDAER_DESCRIPTION','zh_Hans_CN','讨厌科研值低下的文明'),

--海姆达尔外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','嗯，我会协助你'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','我正在收集实验数据，没空'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','我想邀请你测试一些新型作战武器'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','好，那现在开始吧'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','没事，不用在意'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','可别小看了科学家'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','很可惜，你没有什么研究价值'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','好，我的实验正好缺一些人手'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','正在做实验，请不要打扰我'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','这是马场的明信片，你应该会喜欢的，对吧？'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','我可没功夫管这些'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','这里不欢迎你！'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','海姆达尔，我现在要去整理实验数据，你有什么事情嘛？'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','这里是我们的城市，您可以随便参观'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','嗯，很乐意'),
--遇见人类，互相交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','交换一下城市位置吧，有空我会去你那儿看看'),
--请求结盟
('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','我想和你商量一件事情，请问你愿不愿意为科学事业献身，成为我的研究对象吗？'),
--警告玩家边境部队太多
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','你想对一个科学家下手？'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','嗯，希望你能有所行动'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','你的扩张已经严重影响到我的实验场地了，我希望你能去别处'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','好吧，后果自负'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','我知道我无法阻止你的好奇心，但窃取秘密对你没什么好处，知道的越少对你越好...'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','那就再来试试看吧'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','科学才是真谛，请停止传播你的邪教理论！'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','这么不愿意放弃吗？'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','科学...拒绝了我...'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_NEUTRAL','zh_Hans_CN','谢谢'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_HAPPY','zh_Hans_CN','谢谢'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_UNHAPPY','zh_Hans_CN','谢谢'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_NEUTRAL','zh_Hans_CN','看来还需要一个更合理的理由'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_HAPPY','zh_Hans_CN','看来还需要一个更合理的理由'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HAIMUDAER_AETHERGAZER_UNHAPPY','zh_Hans_CN','看来还需要一个更合理的理由'),
-- 议程好感，不用写，因为没有
-- ('LOC_DIPLO_KUDO_EXIT_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','这是，好温暖'),
--议程厌恶
('LOC_DIPLO_WARNING_EXIT_LEADER_HAIMUDAER_AETHERGAZER_ANY','zh_Hans_CN','你为什么对待科学如此怠慢？'),
--议程好感显示，不用写，因为没有
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_PAINFUL_MEMORIES_HAPPY','zh_Hans_CN','海拉很高兴您没有派遣使者刺探她任何的消息'),
--议程厌恶显示
('LOC_DIPLO_MODIFIER_DESCRIPTION_HAIMUDAER_SAD','zh_Hans_CN','海姆达尔对于你的科技滞后表示强烈不满'),
('LOC_ABILITY_HAIMUDAER_NO_MAINTENANCE_FOR_XUNLIZHIHUAN_NAME','zh_Hans_CN','单位+15[ICON_Gold]金币');





-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),