-- TEXT_AETHERGAZER_EXPANSION_XI
-- Author: HK433
-- DateCreated: 2/29/2024 10:37:33 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
--英招外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','同意'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','天禄贸易的闲人已经够多了，不缺你一个'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','天禄贸易想跟您做笔交易，是禄良委托我来跟你交涉，这是协议，请您过目'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','合作愉快'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','这份方案不够合适吗？好的，我稍后再提交一份新的给您'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','计划外的战斗，看来得重新安排日程了'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','接得下我这招吗？'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','明白'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','我没空招待你这些使者，抱歉'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','虚恒的商界代表有意向您商谈贸易协定'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','啊，如此浪费时间的行为，恕我不奉陪了'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','事态有些棘手了'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','把这些资料送到四方院去...您好，工作繁忙有失远迎'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','如果你想参观虚恒的话请自便'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','嗯，非常悠闲的城市'),
--遇见人类，互相交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','在地图上标注下你们的位置吧，晚些时候我会派遣天禄贸易的代表进驻的'),
--请求结盟
-- ('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN',''),
--警告玩家边境部队太多
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','这么多人啊，我没空招待'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','请尽快吧'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','恕我直言，你应该另寻他处建立据点'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','无妨'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','让你间谍滚出我们的城市！我可没有耐心处理这些事情'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','休怪我不客气'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','有信仰是好事，但强加于别人这是否不妥？'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','执迷不悟...哎...'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','我，不甘心...'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_NEUTRAL','zh_Hans_CN','我代表天禄贸易感谢您能同意这次交易'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_HAPPY','zh_Hans_CN','我代表天禄贸易感谢您能同意这次交易'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_UNHAPPY','zh_Hans_CN','我代表天禄贸易感谢您能同意这次交易'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_NEUTRAL','zh_Hans_CN','是我们考虑不周，下次我会带来新的贸易协议'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_HAPPY','zh_Hans_CN','是我们考虑不周，下次我会带来新的贸易协议'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_YINGZHAO_AETHERGAZER_UNHAPPY','zh_Hans_CN','是我们考虑不周，下次我会带来新的贸易协议'),
--议程好感
('LOC_DIPLO_KUDO_EXIT_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','感谢您对天禄贸易的信任'),
--议程厌恶
-- ('LOC_DIPLO_WARNING_EXIT_LEADER_YINGZHAO_AETHERGAZER_ANY','zh_Hans_CN','这个世界的商机无处不在，然而你的探险家从未踏出过自己领土半步，唉（叹气）'),
--议程好感显示
('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_YINGZHAO_HAPPY','zh_Hans_CN','英招喜欢宣布友好的文明'),
--议程厌恶显示
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_YINGZHAO_SAD','zh_Hans_CN','禄良对你落后的探索地图进度感到失望'),
--文明名字
('LOC_CIVILIZATION_AETHERGAZER_GREY_YINGZHAO_NAME','zh_Hans_CN','天垣神域♪'),
('LOC_CIVILIZATION_AETHERGAZER_GREY_YINGZHAO_CAPITALNAME','zh_Hans_CN','神域·天垣'),
--领袖名字
('LOC_LEADER_YINGZHAO_AETHERGAZER_NAME','zh_Hans_CN','英招'),
--英招
('LOC_PEDIA_LEADERS_PAGE_LEADER_YINGZHAO_AETHERGAZER_QUOTE','zh_Hans_CN','天禄贸易，英招....您还想知道什么吗？'),
('LOC_TRAIT_LEADER_YINGZHAO_AETHERGAZER_NAME','zh_Hans_CN','玄司棍法'),
('LOC_TRAIT_LEADER_YINGZHAO_AETHERGAZER_DESCRIPTION','zh_Hans_CN','创建首都后立即获得禄良、英招，距离{LOC_DISTRICT_CITY_CENTER_NAME}区域三个陆地单元格获得铁路。每次您训练一个建造者和开拓者，都可以再获得一个建造者和开拓者。建造者+2[Icon_Movement]移速，虚恒矿山-1[ICON_Production]生产力+3[ICON_Faith]信仰。目的地城市每个矿山或虚恒矿山可使你的贸易路线为双方的城市+1[ICON_Production]生产力，购买商人[ICON_Gold]费用-100%'),
('LOC_LOADING_INFO_LEADER_YINGZHAO_AETHERGAZER','zh_Hans_CN','素质良好的助手，可以提升我的工作效率——英招'),
('LOC_AGENDA_YINGZHAO_NAME','zh_Hans_CN','礼尚往来'),
('LOC_AGENDA_YINGZHAO_DESCRIPTION','zh_Hans_CN','喜欢宣布友好的文明');


--+2[ICON_Food]粮食+2[ICON_Production]生产力+2[ICON_Faith]信仰