-- TEXT_AETHERGAZER_EXPANSION_I
-- Author: HK433
-- DateCreated: 7/23/2023 1:47:05 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
--外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','请多指教~'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','抱歉...我完全不明白你在说什么'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','怎么说呢，像是触碰到了命运般的感觉...'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','交给我吧，我会守护好你的'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','欸？为什么啊....'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','我会打败你的！'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','我的战斗不是为了破坏，而是为了更好的守护他人！'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','我们的关系好像更好了一些呢！'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','你这么着急，是带我去吃东西吗？（故意岔开话题）'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','这是艾因索菲烤肉店的打折卷，可以的话能陪我一起去吗？'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','欸？（疑惑）'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','请不要再来伤害我的朋友！'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','您好，我是薇儿丹蒂，很高兴认识你！'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','你想参观一下艾因索菲吗？'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','好啊，话说你们这里有烤肉店嘛？'),
--遇见人类，交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','你们的城市也有我好多没见过的东西...'),
--请求结盟
('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','守护他人的理想不是说说就能做到的，我也不知道我究竟能做到什么地步，但我会拼尽全力！'),
--移开边境军队
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','无论什么样的攻击，我都会接给你看！'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','希望你能信守承诺'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','请你不要继续下去了'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','距离产生美，难道你不是这么认为的嘛？'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','你这样的行为和视骸没什么两样，请你的情报员离开艾因索菲！'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','什么！？（震惊）'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','请不要将你的思想强加于我，守护的信念是无法被改变的！'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','这样只会害了你'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','不能继续...保护大家了...'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','谢谢你'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','等你决定好就来告诉我吧'),
--议程好感
('LOC_DIPLO_KUDO_EXIT_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','我们是并肩作战的伙伴嘛，所以你不用和我客气，有什么事情都可以跟我说！'),
-- 议程厌恶
-- ('LOC_DIPLO_WARNING_EXIT_LEADER_WEIERDANDI_AETHERGAZER_ANY','zh_Hans_CN','没有厌恶选项，不写'),
--议程好感显示
('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_WEIERDANDI_HAPPY','zh_Hans_CN','您是薇儿丹蒂最好的邻居'),
--议程厌恶显示
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_PAINFUL_MEMORIES_SAD','zh_Hans_CN','没有厌恶选项，不写'),
---
('LOC_TRAIT_LEADER_WEIERDANDI_AETHERGAZER_DESCRIPTION','zh_Hans_CN','创建首都后立即获得奥西里斯、薇儿丹蒂，研究防御战术后即可种树。城市每建成一个区域都能获得一个建造者，建造者[ICON_Movement]+1移动力且无视地形和跨河的[ICON_Movement]移动惩罚'),
('LOC_TRAIT_LEADER_WEIERDANDI_AETHERGAZER_NAME','zh_Hans_CN','信念守护'),
('LOC_LEADER_WEIERDANDI_AETHERGAZER_NAME','zh_Hans_CN','薇儿丹蒂'),
---
('LOC_LOADING_INFO_LEADER_WEIERDANDI_AETHERGAZER','zh_Hans_CN','我不希望自己身边的人受到伤害，不想看到自己的故乡被视骸摧毁，但在这个世界的某处却有人在遭受着这种事，我无法在知道这一切后坐视不管...——薇儿丹蒂'),
('LOC_PEDIA_LEADERS_PAGE_LEADER_WEIERDANDI_AETHERGAZER_QUOTE','zh_Hans_CN','我会守护好大家的！'),
('LOC_AGENDA_WEIERDANDI_NAME','zh_Hans_CN','守护一切'),
('LOC_AGENDA_WEIERDANDI_DESCRIPTION','zh_Hans_CN','对自己周边的邻国非常友善'),
--薇儿丹蒂
('LOC_CIVILIZATION_AETHERGAZER_GREEN_WEIERDANDI_NAME','zh_Hans_CN','圣树神域♭'),
('LOC_CIVILIZATION_AETHERGAZER_GREEN_WEIERDANDI_CAPITALNAME','zh_Hans_CN','神域·圣树');
-- ('','zh_Hans_CN',''),
-- ('','zh_Hans_CN',''),



