-- TEXT_AETHERGAZER_EXPANSION_PART_S_WEIERDANDI_TWO
-- Author: HK433
-- DateCreated: 6/26/2024 4:05:54 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
--外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','嗯，请多指教'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','现在还不是说这个的时候'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','无论回应我的是什么，都请成为......「我」的力量，这样我才能更好的守护你'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','交给我吧'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','....。'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','我不会再退缩了！'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','这就是你的结局！'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','嗯，深空之眼非常欢迎你使者的到来'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','你这么着急，是要带我去吃东西吗？（故意岔开话题）'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','这是我自己准备的小礼物，请你收下'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','我没有做过对不起你的事情'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','你终将付出代价'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','深空之眼，薇儿丹蒂，你好，陌生人。'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','你想参观一下艾因索菲吗？'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','可以，你们这里有...烤肉店嘛？'),
--遇见人类，交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','很漂亮的城市，这让我想起以前待过的地方...'),
--请求结盟，没用到过
-- ('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','守护他人的理想不是说说就能做到的，我也不知道我究竟能做到什么地步，但我会拼尽全力！'),
--移开边境军队
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','我不接受挑衅，如果你想发动战争，就放马过来。'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','希望你能信守承诺'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','这里是我们深空之眼的地盘'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','休怪我不客气了'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','你这样的行为和视骸没什么两样，请你的情报员离开艾因索菲！'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','竟然....'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','守护的信念是无法被改变的！'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','这样只会害了你'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','管理员...还在等我...'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_NEUTRAL','zh_Hans_CN','嗯，谢谢'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_HAPPY','zh_Hans_CN','嗯，谢谢'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_UNHAPPY','zh_Hans_CN','嗯，谢谢'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_NEUTRAL','zh_Hans_CN','没事，那就等下次吧'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_HAPPY','zh_Hans_CN','没事，那就等下次吧'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_UNHAPPY','zh_Hans_CN','没事，那就等下次吧'),
--议程好感
('LOC_DIPLO_KUDO_EXIT_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','当时轻松许下的「守护大家」之类的愿望，现在看来确实很美好，但也很艰难。不过我相信，只要大家还在一起，这些愿望就一定能够实现'),
-- 议程厌恶
-- ('LOC_DIPLO_WARNING_EXIT_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_ANY','zh_Hans_CN','没有厌恶选项，不写'),
--议程好感显示
('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_S_WEIERDANDI_HAPPY','zh_Hans_CN','您是薇儿丹蒂最好的邻居'),
--议程厌恶显示
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_PAINFUL_MEMORIES_SAD','zh_Hans_CN','没有厌恶选项，不写'),
---
('LOC_TRAIT_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_DESCRIPTION','zh_Hans_CN','除了拥有黯耀·薇儿丹蒂的领袖技能外，初始获得+4[ICON_VisLimited]外交能见度和1个间谍（并增加1个间谍容量）。所有单位上船下船时[ICON_Movement]无移动力消耗且防御时+10[ICON_Strength]战斗力。研究{LOC_TECH_SHIPBUILDING_NAME}后，所有单位拥有进入海岸、海洋单元格的能力。城市内所有单元格+2[ICON_Faith]信仰，每个政体都会额外获得一个通用槽。领土内间谍活动-4等级，间谍行动时间减少75%且部署在其他城市无需消耗时间，进攻性间谍任务成功时，获得目标城市该回合[ICON_Gold]金币和[ICON_Faith]信仰值的1000%。有两个或以上[ICON_GreatWork_Sculpture]巨作槽位的奇观和建筑自动获得[ICON_ThemeBonus_Active]主体化。所有[ICON_GreatWork_Artifact]文物+3[ICON_Food]食物+3[ICON_Production]生产力+3[ICON_Gold]金币。购买剧院广场区域建筑和考古学家的[ICON_Gold]费用-100%，考古学家+20[ICON_Movement]移动力'),
('LOC_TRAIT_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_NAME','zh_Hans_CN','刹那的辉光'),
('LOC_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_NAME','zh_Hans_CN','薇儿丹蒂（圣歌精灵）'),
('LOC_LEADER_WEIERDANDI_AETHERGAZER_NAME','zh_Hans_CN','薇儿丹蒂（旧誓）'),
---
('LOC_PEDIA_LEADERS_PAGE_LEADER_S_WEIERDANDI_TWO_AETHERGAZER_QUOTE','zh_Hans_CN','我很清楚，自己的身份和使命'),

('LOC_VIZSOURCE_S_WEIERDANDI_TWO_AETHERGAZER','zh_Hans_CN','薇儿丹蒂（圣歌精灵）初始的情报优势'),
('LOC_VIZSOURCE_ACTION_S_WEIERDANDI_TWO_AETHERGAZER','zh_Hans_CN','使用深空之眼领袖薇儿丹蒂（圣歌精灵）'),
('LOC_GOSSIP_SOURCE_S_WEIERDANDI_TWO_AETHERGAZER','zh_Hans_CN','科尔盖特工发来密电'),
('LOC_S_WEIERDANDI_TWO_ADD_10_DEF_DESCRIPTION','zh_Hans_CN','+{1_Amount} [ICON_Strength] 战斗力，来自薇儿丹蒂（圣歌精灵）领袖特性');
