-- TEXT_AETHERGAZER_EXPANSION_PART_ZHIMING
-- Author: HK433
-- DateCreated: 6/29/2024 9:29:36 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
--执明外交
--同意蓝脸
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','为什么不早说，我的意思是为什么现在才告诉我？'),
--拒绝蓝脸
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','无意义的事情'),
--请求蓝脸
('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','四方院愿意给予你一些特殊权利，但这并不是我的主意....'),
--人类接受结盟
('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','嗯，我明白了'),
--人类拒绝结盟
('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','我早就跟那些人说过不要在你身上浪费时间'),
--被宣
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','休想动我一根毫毛！'),
--主宣
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','你就不应该存在这个世界上！'),
--接受使者
('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','让他们自己进来坐着，我还要做研究.....'),
--拒绝使者
('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','你找四方院其他人问问吧，我没空'),
--向人类派遣使者
('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','四方院的科研人员正在前往你的领地，希望你能好好招待这些人'),
--被谴责
('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','粗鄙之人，竟敢出言不逊'),
--谴责人类
('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','无耻之徒！'),
--遇见人类
('LOC_DIPLO_FIRST_MEET_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','我教你过多少次了，你怎么还会弄错？都拿回去重新审查...你好，你找我有什么事情'),
--遇见人类，提供最近城市位置
('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','是来参观四方院嘛，随我来就是'),
--遇见人类，玩家提供位置
('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','嗯，可以'),
--遇见人类，互相交换位置
('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','你是从哪里来的？能在地图上标注下位置嘛？'),
--请求结盟
-- ('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN',''),
--警告玩家边境部队太多
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','这么多军队，是来袭击我们的嘛？'),
--玩家同意撤走
('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','真的嘛？我怎么不信'),
--警告玩家不要在我周边建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','你的扩张已经影响到我们了'),
--玩家拒绝建城
('LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','既然这样，那我也没什么话好说的了'),
--警告玩家间谍在AI家里
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','盗取四方院的机密，可不是闹着玩的，我劝你下次别再这样了'),
--玩家拒绝间谍
('LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','我也没什么好说的了'),
--警告玩家不允许传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','你们的宗教人士什么时候离开？'),
--玩家继续传教
('LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','.....。'),
--战败
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','要不是因为这副身体....'),
--同意交易
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_ZHIMING_AETHERGAZER_NEUTRAL','zh_Hans_CN','合作愉快，这对我们俩都有好处'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_ZHIMING_AETHERGAZER_HAPPY','zh_Hans_CN','合作愉快，这对我们俩都有好处'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_ZHIMING_AETHERGAZER_UNHAPPY','zh_Hans_CN','合作愉快，这对我们俩都有好处'),
--拒绝交易
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_ZHIMING_AETHERGAZER_NEUTRAL','zh_Hans_CN','那就算了'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_ZHIMING_AETHERGAZER_HAPPY','zh_Hans_CN','那就算了'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_ZHIMING_AETHERGAZER_UNHAPPY','zh_Hans_CN','那就算了'),
--议程好感
-- ('LOC_DIPLO_KUDO_EXIT_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','感谢您对天禄贸易的信任'),
--议程厌恶
('LOC_DIPLO_WARNING_EXIT_LEADER_ZHIMING_AETHERGAZER_ANY','zh_Hans_CN','我居然和一个完全没有素养的家伙商讨国际事务，真是可笑'),
--议程好感显示
-- ('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_ZHIMING_HAPPY','zh_Hans_CN','英招喜欢宣布友好的文明'),
--议程厌恶显示
('LOC_DIPLO_MODIFIER_DESCRIPTION_AGENDA_ZHIMING_SAD','zh_Hans_CN','执明对你低下的文化值嗤之以鼻'),
--文明名字
('LOC_CIVILIZATION_AETHERGAZER_GREY_ZHIMING_NAME','zh_Hans_CN','天垣神域-玄机'),
('LOC_CIVILIZATION_AETHERGAZER_GREY_ZHIMING_CAPITALNAME','zh_Hans_CN','神域·天垣'),
--领袖名字
('LOC_LEADER_ZHIMING_AETHERGAZER_NAME','zh_Hans_CN','执明'),
--英招
('LOC_PEDIA_LEADERS_PAGE_LEADER_ZHIMING_AETHERGAZER_QUOTE','zh_Hans_CN','唔...你怎么像小孩子一样.....？幼稚。'),
('LOC_TRAIT_LEADER_ZHIMING_AETHERGAZER_NAME','zh_Hans_CN','颛顼秘法'),
('LOC_TRAIT_LEADER_ZHIMING_AETHERGAZER_DESCRIPTION','zh_Hans_CN','创建首都后立即获得执明、庚辰，拥有四方院的城市+2[ICON_GreatWriter]大作家点数，图书馆+1[ICON_GreatWriter]大作家点数+3[ICON_GreatWork_Sculpture]巨作槽位，著作+3[ICON_Science]科研值+3[ICON_Culture]文化值-100%[ICON_TOURISM]旅游业绩。战斗胜利后，获得等同于被击杀单位[ICON_Strength]战斗力20%的[ICON_GreatWriter]大作家点数，所有单位击杀蛮族单位时可正常获得经验值。循理之环每回合-5[ICON_Gold]金币但购买[ICON_Gold]费用-100%，建造宇航中心+9999%[ICON_Production]生产力，执行太空项目时+7000%[ICON_Production]生产力'),
('LOC_LOADING_INFO_LEADER_ZHIMING_AETHERGAZER','zh_Hans_CN','磁性衬板在自然作用下的耐久性？呼......这我自然知道，但我现在不想告诉你。自己想吧。——执明'),
('LOC_AGENDA_ZHIMING_NAME','zh_Hans_CN','知识渊博'),
('LOC_AGENDA_ZHIMING_DESCRIPTION','zh_Hans_CN','讨厌文化值低下的文明'),
('LOC_ABILITY_ZHIMING_5_MAINTENANCE_FOR_XUNLIZHIHUAN_NAME','zh_Hans_CN','[COLOR:ResMilitaryLabelCS]每回合-5[ICON_Gold]金币（维护费）[ENDCOLOR]，来自执明的领袖特性');


--+2[ICON_Food]粮食+2[ICON_Production]生产力+2[ICON_Faith]信仰