-- TEXT_GIRLFRONTLINE_CORE
-- Author: HK433
-- DateCreated: 10/1/2023 8:50:13 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText(Tag,Language,Text)
VALUES
('LOC_ABILITY_NO_TERRAIN_MOVEMENT_DEBUFF_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','单位[ICON_Movement]移动不受地形惩罚'),
('LOC_ABILITY_ANTITANK_SQUAD_ADD_32_COMBAT_VS_CLASS_HEAVY_CAVALRY_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','对抗重骑兵+12[ICON_Strength]战斗力'),
('LOC_ABILITY_ANTITANK_SQUAD_ADD_32_COMBAT_VS_CLASS_LIGHT_CAVALRY_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','对抗轻骑兵+12[ICON_Strength]战斗力'),
('LOC_ABILITY_ANTITANK_SQUAD_ADD_65_COMBAT_VS_CLASS_GIANT_DEATH_ROBOT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','对末日机甲+65[ICON_Strength]战斗力'),
('LOC_ABILITY_NO_DEBUFF_VS_DISTRICT_RANGED_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','单位对城防造成全额伤害'),
('LOC_ABILITY_CIVIC_NATIONALISM_ADD_7_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_CIVIC_NATIONALISM_NAME}：单位+7[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-3[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_CIVIC_MOBILIZATION_ADD_10_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_CIVIC_MOBILIZATION_NAME}：单位+10[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-3[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_TECH_IRON_WORKING_ADD_16_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_TECH_IRON_WORKING_NAME}：单位+16[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-1[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_TECH_APPRENTICESHIP_ADD_9_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_TECH_APPRENTICESHIP_NAME}：单位+9[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-1[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_TECH_GUNPOWDER_ADD_10_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_TECH_GUNPOWDER_NAME}：单位+10[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-1[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_TECH_MILITARY_SCIENCE_ADD_10_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_TECH_MILITARY_SCIENCE_NAME}：单位+10[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-1[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_TECH_REPLACEABLE_PARTS_ADD_10_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_TECH_REPLACEABLE_PARTS_NAME}：单位+10[ICON_Strength]战斗力，[COLOR:ResMilitaryLabelCS]每回合-1[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_TECH_COMPOSITES_ADD_25_COMBAT_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','{LOC_TECH_COMPOSITES_NAME}：单位+25[ICON_Strength]战斗力,[COLOR:ResMilitaryLabelCS]每回合-1[ICON_Gold]金币（维护费）[ENDCOLOR]'),
('LOC_ABILITY_CIVIC_NATIONALISM_ADD_7_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_CIVIC_NATIONALISM_NAME}'),
('LOC_ABILITY_CIVIC_MOBILIZATION_ADD_10_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_CIVIC_MOBILIZATION_NAME}'),
('LOC_ABILITY_TECH_IRON_WORKING_ADD_16_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_TECH_IRON_WORKING_NAME}'),
('LOC_ABILITY_TECH_APPRENTICESHIP_ADD_9_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_TECH_APPRENTICESHIP_NAME}'),
('LOC_ABILITY_TECH_GUNPOWDER_ADD_10_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_TECH_GUNPOWDER_NAME}'),
('LOC_ABILITY_TECH_MILITARY_SCIENCE_ADD_10_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_TECH_MILITARY_SCIENCE_NAME}'),
('LOC_ABILITY_TECH_REPLACEABLE_PARTS_ADD_10_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_TECH_REPLACEABLE_PARTS_NAME}'),
('LOC_ABILITY_TECH_COMPOSITES_ADD_25_COMBAT_GIRLFRONTLINE_COMBAT_DESCRIPTION','zh_Hans_CN','+{1_Amount}战斗力，来自{LOC_TECH_COMPOSITES_NAME}'),
('LOC_UNIT_NEW_ASSAULT_SQUAD_NAME','zh_Hans_CN','动员突击战术人形小队'),
('LOC_UNIT_NEW_ASSAULT_SQUAD_DESCRIPTION','zh_Hans_CN','临时动员的战术人形，能对城墙造成全额伤害[NEWLINE][COLOR:ResMilitaryLabelCS]该单位无法获得任何经验[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_ASSAULT_SQUAD_NAME','zh_Hans_CN','老练突击战术人形小队'),
('LOC_UNIT_EXPERIENCED_ASSAULT_SQUAD_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，能对城墙造成全额伤害'),
('LOC_UNIT_ADVANCED_ASSAULT_SQUAD_NAME','zh_Hans_CN','进阶突击战术人形小队'),
('LOC_UNIT_ADVANCED_ASSAULT_SQUAD_DESCRIPTION','zh_Hans_CN','通过模拟训练，且有一定的实战经验的战术人形，能对城墙造成全额伤害'),
('LOC_UNIT_ELITE_ASSAULT_SQUAD_NAME','zh_Hans_CN','精英突击战术人形小队'),
('LOC_UNIT_ELITE_ASSAULT_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，能对城墙造成全额伤害'),
('LOC_UNIT_NEW_TACTICS_SQUAD_NAME','zh_Hans_CN','征召战术人形小队'),
('LOC_UNIT_NEW_TACTICS_SQUAD_DESCRIPTION','zh_Hans_CN','临时调动负责后勤的战术人形，常规款战术人形，拥有[ICON_Range]范围为2的[ICON_Ranged]远程战斗力，但[ICON_Ranged]远程战斗力较弱[NEWLINE][COLOR:ResMilitaryLabelCS]该单位无法获得任何经验[ENDCOLOR][NEWLINE][COLOR:ResMilitaryLabelCS]研究{LOC_TECH_IRON_WORKING_NAME}、{LOC_TECH_APPRENTICESHIP_NAME}能使单位战斗力提升[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_TACTICS_SQUAD_NAME','zh_Hans_CN','老练战术人形小队'),
('LOC_UNIT_EXPERIENCED_TACTICS_SQUAD_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，常规款战术人形，拥有[ICON_Range]范围为2的[ICON_Ranged]远程战斗力，但[ICON_Ranged]远程战斗力较弱[NEWLINE][COLOR:ResMilitaryLabelCS]研究{LOC_TECH_MILITARY_SCIENCE_NAME}能使单位战斗力提升[ENDCOLOR]'),
('LOC_UNIT_ADVANCED_TACTICS_SQUAD_NAME','zh_Hans_CN','进阶战术人形小队'),
('LOC_UNIT_ADVANCED_TACTICS_SQUAD_DESCRIPTION','zh_Hans_CN','通过模拟训练，且有一定的实战经验的战术人形，常规款战术人形，拥有[ICON_Range]范围为2的[ICON_Ranged]远程战斗力，但[ICON_Ranged]远程战斗力较弱'),
('LOC_UNIT_ELITE_TACTICS_SQUAD_NAME','zh_Hans_CN','精英战术人形小队'),
('LOC_UNIT_ELITE_TACTICS_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，常规款战术人形，拥有[ICON_Range]范围为2的[ICON_Ranged]远程战斗力，但[ICON_Ranged]远程战斗力较弱'),
('LOC_UNIT_NEW_ARMORED_SQUAD_NAME','zh_Hans_CN','新建重装战术人形小队'),
('LOC_UNIT_NEW_ARMORED_SQUAD_DESCRIPTION','zh_Hans_CN','从重型建造崭新出厂的战术人形，未通过任何测试，拥有比常规战术人形更厚重的装甲，且拥有[ICON_Range]范围为1的[ICON_Ranged]远程战斗力，但[ICON_Movement]移动力缓慢[NEWLINE][COLOR:ResMilitaryLabelCS]该单位无法获得任何经验[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_ARMORED_SQUAD_NAME','zh_Hans_CN','老练重装战术人形小队'),
('LOC_UNIT_EXPERIENCED_ARMORED_SQUAD_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，拥有比常规战术人形更厚重的装甲，且拥有[ICON_Range]范围为1的[ICON_Ranged]远程战斗力，但[ICON_Movement]移动力缓慢'),
('LOC_UNIT_ADVANCED_ARMORED_SQUAD_NAME','zh_Hans_CN','进阶重装战术人形小队'),
('LOC_UNIT_ADVANCED_ARMORED_SQUAD_DESCRIPTION','zh_Hans_CN','通过模拟训练，且有一定的实战经验的战术人形，拥有比常规战术人形更厚重的装甲，且拥有[ICON_Range]范围为1的[ICON_Ranged]远程战斗力，但[ICON_Movement]移动力缓慢'),
('LOC_UNIT_ELITE_ARMORED_SQUAD_NAME','zh_Hans_CN','精英重装战术人形小队'),
('LOC_UNIT_ELITE_ARMORED_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，拥有比常规战术人形更厚重的装甲，且拥有[ICON_Range]范围为1的[ICON_Ranged]远程战斗力，但[ICON_Movement]移动力缓慢'),
('LOC_UNIT_NEW_RECON_SQUAD_NAME','zh_Hans_CN','征召侦查战术人形小队'),
('LOC_UNIT_NEW_RECON_SQUAD_DESCRIPTION','zh_Hans_CN','临时调动负责后勤的战术人形,拥有额外的视野，且视野能穿过任何地形，单位[ICON_Movement]移动不受地形惩罚[NEWLINE][COLOR:ResMilitaryLabelCS]该单位无法获得任何经验[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_RECON_NAME','zh_Hans_CN','老练侦查战术人形小队'),
('LOC_UNIT_EXPERIENCED_RECON_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，拥有额外的视野，且视野能穿过任何地形，单位[ICON_Movement]移动不受地形惩罚'),
('LOC_UNIT_ADVANCED_RECON_SQUAD_NAME','zh_Hans_CN','进阶侦查战术人形小队'),
('LOC_UNIT_ADVANCED_RECON_SQUAD_DESCRIPTION','zh_Hans_CN','通过模拟训练，且有一定的实战经验的战术人形， 拥有额外的视野，且视野能穿过任何地形，单位[ICON_Movement]移动不受地形惩罚'),
('LOC_UNIT_ELITE_RECON_SQUAD_NAME','zh_Hans_CN','精英侦查战术人形小队'),
('LOC_UNIT_ELITE_RECON_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，拥有额外的视野，且视野能穿过任何地形，单位[ICON_Movement]移动不受地形惩罚'),
('LOC_UNIT_NEW_SNIPER_SQUAD_NAME','zh_Hans_CN','动员狙击战术人形小队'),
('LOC_UNIT_NEW_SNIPER_SQUAD_DESCRIPTION','zh_Hans_CN','临时调动负责后勤的战术人形，拥有[ICON_Range]范围为3的[ICON_Ranged]远程攻击，[COLOR:ResMilitaryLabelCS]但近战战斗力极其低下[NEWLINE]该单位无法获得任何经验[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_SNIPER_SQUAD_NAME','zh_Hans_CN','老练狙击战术人形小队'),
('LOC_UNIT_EXPERIENCED_SNIPER_SQUAD_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，拥有[ICON_Range]范围为3的[ICON_Ranged]远程攻击，[COLOR:ResMilitaryLabelCS]但近战战斗力极其低下[ENDCOLOR]'),
('LOC_UNIT_ADVANCED_SNIPER_SQUAD_NAME','zh_Hans_CN','进阶狙击战术人形小队'),
('LOC_UNIT_ADVANCED_SNIPER_SQUAD_DESCRIPTION','zh_Hans_CN','通过模拟训练，且有一定的实战经验的战术人形，拥有[ICON_Range]范围为4的[ICON_Ranged]远程攻击，[COLOR:ResMilitaryLabelCS]但近战战斗力极其低下[ENDCOLOR]'),
('LOC_UNIT_ELITE_SNIPER_SQUAD_NAME','zh_Hans_CN','精英狙击战术人形小队'),
('LOC_UNIT_ELITE_SNIPER_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，拥有[ICON_Range]范围为4的[ICON_Ranged]远程攻击，[COLOR:ResMilitaryLabelCS]但近战战斗力极其低下[ENDCOLOR]'),
('LOC_UNIT_NEW_ANTITANK_SQUAD_NAME','zh_Hans_CN','新建反坦克战术人形小队'),
('LOC_UNIT_NEW_ANTITANK_SQUAD_DESCRIPTION','zh_Hans_CN','从重型建造崭新出厂的战术人形，未通过任何测试，拥有[ICON_Range]范围为2的[ICON_Bombard]轰炸攻击，对抗骑兵+12[ICON_Strength]战斗力[NEWLINE][COLOR:ResMilitaryLabelCS]该单位无法获得任何经验[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_ANTITANK_SQUAD_NAME','zh_Hans_CN','老练反坦克战术人形小队'),
('LOC_UNIT_EXPERIENCED_ANTITANK_SQUAD_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，拥有[ICON_Range]范围为3的[ICON_Bombard]轰炸攻击，对抗骑兵+12[ICON_Strength]战斗力'),
('LOC_UNIT_ADVANCED_ANTITANK_SQUAD_NAME','zh_Hans_CN','进阶反坦克战术人形小队'),
('LOC_UNIT_ADVANCED_ANTITANK_SQUAD_DESCRIPTION','zh_Hans_CN','过模拟训练，且有一定的实战经验的战术人形，拥有[ICON_Range]范围为4的[ICON_Bombard]轰炸攻击，对抗骑兵+12[ICON_Strength]战斗力'),
('LOC_UNIT_ELITE_ANTITANK_SQUAD_NAME','zh_Hans_CN','精英反坦克战术人形小队'),
('LOC_UNIT_ELITE_ANTITANK_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，拥有[ICON_Range]范围为5的[ICON_Bombard]轰炸攻击，对抗骑兵+12[ICON_Strength]战斗力，对抗末日机甲+67[ICON_Strength]战斗力'),
('LOC_UNIT_SPECIAL_G41_NAME','zh_Hans_CN','G41'),
('LOC_UNIT_SPECIAL_G41_DESCRIPTION','zh_Hans_CN','活泼可爱的性格，带着十分粘人的忠犬属性，接受的命令一定会达成，并喜欢指挥官能摸自己的头作为奖励。'),
('LOC_UNIT_SPECIAL_TMP_NAME','zh_Hans_CN','TMP'),
('LOC_UNIT_SPECIAL_TMP_DESCRIPTION','zh_Hans_CN','生性胆怯，容易害羞的人形少女，是个沉迷于自我妄想的妄想派，常常喋喋不休地自言自语自己的想法，一旦发现被人听见又会陷入手足无措的地步。但是如果把她逼入“绝境”的话……请做好事态无法控制的心理准备吧。'),
('LOC_TRAIT_GIRLFRONTLINE_SQUAD_NAME','zh_Hans_CN','格里芬战术人形小队'),
('LOC_TRAIT_GIRLFRONTLINE_SQUAD_DESCRIPTION','zh_Hans_CN','无法建造原版所有陆地单位和开拓者，但能建造战术人形和爬行者[NEWLINE]所有军事单位+50%战斗经验，但[COLOR:ResMilitaryLabelCS]部分战术人形无法获得经验[ENDCOLOR]'),
('LOC_ROMOTION_CLASS_ASSAULT_SQUAD_NAME','zh_Hans_CN','近战攻城'),
('LOC_ABILITY_CAN_NOT_MELEE_ATTACK_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','单位无法使用[ICON_Strength]近战攻击'),
('LOC_UNIT_MCV_NAME','zh_Hans_CN','爬行者'),
('LOC_UNIT_MCV_DESCRIPTION','zh_Hans_CN','拥有一定防御能力的特色开拓者，无法使用近战攻击。该单位[COLOR:ResMilitaryLabelCS]造价非常昂贵[ENDCOLOR]，但永不涨价'),
('LOC_DISTRICT_COMMERCIAL_HUB_FRONTLINECAMP_NAME','zh_Hans_CN','后勤仓库'),
('LOC_DISTRICT_COMMERCIAL_HUB_FRONTLINECAMP_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_COMMERCIAL_HUB_NAME}，造价更低，建成后+1[ICON_TradeRoute]贸易容量，并且赠送一个商人单位，具有独特的[ICON_Gold]金币相邻加成。研究{LOC_TECH_IRON_WORKING_NAME}后，[ICON_Gold]金币相邻加成也提供[ICON_Production]生产力。区域拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为1[ICON_Ranged]远程攻击'),
('LOC_DISTRICT_ENCAMPMENT_FRONTLINECAMP_NAME','zh_Hans_CN','起重机'),
('LOC_DISTRICT_ENCAMPMENT_FRONTLINECAMP_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_ENCAMPMENT_NAME}，初始解锁，可建造在市中心周围，具有独特的[ICON_Production]生产力相邻加成，建成后将释放创建城市时消耗的爬行者。区域仅拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为3[ICON_Ranged]远程攻击'),
('LOC_DISTRICT_INDUSTRIAL_ZONE_FRONTLINECAMP_NAME','zh_Hans_CN','战争工厂'),
('LOC_DISTRICT_INDUSTRIAL_ZONE_FRONTLINECAMP_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_INDUSTRIAL_ZONE_NAME}，需要{LOC_TECH_INDUSTRIALIZATION_NAME}，造价免费且永不涨价，具有独特的[ICON_Production]生产力相邻加成。区域拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为1[ICON_Ranged]远程攻击'),
('LOC_ADJACENCY_PER_DISTRICT_ADD_3_YIELD_PRODUCTION_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Production] 生产力来自相邻的每个区域'),
('LOC_ADJACENCY_PER_DISTRICT_ADD_3_YIELD_GOLD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Gold] 金币来自相邻的每个区域'),
('LOC_ADJACENCY_PER_DISTRICT_ADD_3_YIELD_FOOD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Food] 食物来自相邻的每个区域'),
('LOC_ADJACENCY_MOUNTAIN_ADD_3_YIELD_PRODUCTION_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Production] 生产力来自山脉'),
('LOC_ADJACENCY_WATER_ADD_3_YIELD_PRODUCTION_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Production] 生产力来自水域'),
('LOC_ADJACENCY_MOUNTAIN_ADD_3_YIELD_GOLD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Gold] 金币来自山脉'),
('LOC_ADJACENCY_WATER_ADD_3_YIELD_GOLD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Gold] 金币来自水域'),
('LOC_ADJACENCY_MOUNTAIN_ADD_3_YIELD_FOOD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Food] 食物来自山脉'),
('LOC_ADJACENCY_WATER_ADD_3_YIELD_FOOD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Food] 食物来自水域'),
('LOC_ADJACENCY_RESOURCECLASS_STRATEGIC_ADD_3_YIELD_PRODUCTION_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Production] 生产力来自战略资源'),
('LOC_ADJACENCY_RESOURCECLASS_LUXURY_ADD_3_YIELD_PRODUCTION_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Production] 生产力来自奢侈品资源'),
('LOC_ADJACENCY_RESOURCECLASS_STRATEGIC_ADD_3_YIELD_GOLD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Gold] 金币来自战略资源'),
('LOC_ADJACENCY_RESOURCECLASS_LUXURY_ADD_3_YIELD_GOLD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Gold] 金币来自奢侈品资源'),
('LOC_ADJACENCY_RESOURCECLASS_STRATEGIC_ADD_3_YIELD_FOOD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Food] 食物来自战略资源'),
('LOC_ADJACENCY_RESOURCECLASS_LUXURY_ADD_3_YIELD_FOOD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Food] 食物来自奢侈品资源'),
('LOC_ADJACENCY_PER_WONDER_ADD_3_YIELD_PRODUCTION_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Production] 生产力来自人造奇观'),
('LOC_ADJACENCY_PER_WONDER_ADD_3_YIELD_GOLD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Gold] 金币来自人造奇观'),
('LOC_ADJACENCY_PER_WONDER_ADD_3_YIELD_FOOD_DESCRIPTION','zh_Hans_CN','+{1_num} [ICON_Food] 食物来自人造奇观'),
('LOC_TRAIT_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_NAME','zh_Hans_CN','营地'),
('LOC_TRAIT_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_DESCRIPTION','zh_Hans_CN','城市不会产生厌战情绪，单位无需驻扎在回合开始时恢复生命，已改良的单元格+3[ICON_Gold]金币，+1[icon_Faith]信仰，研究{LOC_TECH_ELECTRICITY_NAME}后再加+2[ICON_Production]生产力。'),
('LOC_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_DESCRIPTION','zh_Hans_CN','格里芬前线战备队营地'),
('LOC_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_ADJECTIVE','zh_Hans_CN','前线战备队营地的'),
('LOC_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_NAME','zh_Hans_CN','前线战备队-营地'),
('LOC_UNIT_SPECIAL_SR3MP_NAME','zh_Hans_CN','SR-3MP'),
('LOC_UNIT_SPECIAL_SR3MP_DESCRIPTION','zh_Hans_CN','活泼张扬、自命不凡的人形，喜欢对他人指手画脚，作战中反而会保持安静，用夸张的手势取而代之，所以姑且也算是个认真负责的战斗者。'),
('LOC_TRAIT_CIVILIZATION_GIRLFRONTLINE_STRATEGYCENTER_NAME','zh_Hans_CN','情报中心'),
('LOC_TRAIT_CIVILIZATION_GIRLFRONTLINE_STRATEGYCENTER_DESCRIPTION','zh_Hans_CN','城市不会产生厌战情绪，单位无需驻扎在回合开始时恢复生命，所有您创建或攻占的城市一开始便拥有贸易站，创建贸易路线后，目的地城市中将立即出现贸易站。领土内间谍活动-4等级，研究{LOC_TECH_STIRRUPS_NAME}，{LOC_TECH_BALLISTICS_NAME}，{LOC_TECH_COMBUSTION_NAME}和{LOC_TECH_COMPOSITES_NAME}分别+1外交能见度'),
('LOC_CIVILIZATION_GIRLFRONTLINE_STRATEGYCENTER_DESCRIPTION','zh_Hans_CN','格里芬前线战备队情报中心'),
('LOC_CIVILIZATION_GIRLFRONTLINE_STRATEGYCENTER_ADJECTIVE','zh_Hans_CN','前线战备队情报中心的'),
('LOC_CIVILIZATION_GIRLFRONTLINE_STRATEGYCENTER_NAME','zh_Hans_CN','前线战备队-情报中心'),
('LOC_VIZSOURCE_TECH_STIRRUPS_GIRLFRONTLINE','zh_Hans_CN','格里芬前线战备队情报中心的情报优势等级1'),
('LOC_VIZSOURCE_ACTION_TECH_STIRRUPS_GIRLFRONTLINE','zh_Hans_CN','使用格里芬情报中心部门的战术人形领袖，研究{LOC_TECH_STIRRUPS_NAME}获得情报优势'),
('LOC_GOSSIP_SOURCE_TECH_STIRRUPS_GIRLFRONTLINE','zh_Hans_CN','您情报中心的记者报道了一则新闻'),
('LOC_VIZSOURCE_TECH_BALLISTICS_GIRLFRONTLINE','zh_Hans_CN','格里芬前线战备队情报中心的情报优势等级2'),
('LOC_VIZSOURCE_ACTION_TECH_BALLISTICS_GIRLFRONTLINE','zh_Hans_CN','使用格里芬情报中心部门的战术人形领袖，研究{LOC_TECH_BALLISTICS_NAME}获得情报优势'),
('LOC_GOSSIP_SOURCE_TECH_BALLISTICS_GIRLFRONTLINE','zh_Hans_CN','您情报中心的线人打听到'),
('LOC_VIZSOURCE_TECH_COMBUSTION_GIRLFRONTLINE','zh_Hans_CN','格里芬前线战备队情报中心的情报优势等级3'),
('LOC_VIZSOURCE_ACTION_TECH_COMBUSTION_GIRLFRONTLINE','zh_Hans_CN','使用格里芬情报中心部门的战术人形领袖，研究{LOC_TECH_COMBUSTION_NAME}获得情报优势'),
('LOC_GOSSIP_SOURCE_TECH_COMBUSTION_GIRLFRONTLINE','zh_Hans_CN','您情报中心的外交官报告到'),
('LOC_VIZSOURCE_TECH_COMPOSITES_GIRLFRONTLINE','zh_Hans_CN','格里芬前线战备队情报中心的情报优势等级4'),
('LOC_VIZSOURCE_ACTION_TECH_COMPOSITES_GIRLFRONTLINE','zh_Hans_CN','使用格里芬情报中心部门的战术人形领袖，研究{LOC_TECH_COMPOSITES_NAME}获得情报优势'),
('LOC_GOSSIP_SOURCE_TECH_COMPOSITES_GIRLFRONTLINE','zh_Hans_CN','您情报中心的特务发来密电'),
('LOC_DISTRICT_CAMPUS_STRATEGYCENTER_NAME','zh_Hans_CN','科技中心'),
('LOC_DISTRICT_CAMPUS_STRATEGYCENTER_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_CAMPUS_NAME}，{LOC_TECH_IRRIGATION_NAME}解锁，造价免费且永不涨价，具有独特的[ICON_Food]食物相邻加成。[ICON_Food]食物相邻加成也提供[ICON_Science]科研和[ICON_Gold]金币。区域拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为1[ICON_Ranged]远程攻击'),
('LOC_DISTRICT_INDUSTRIAL_ZONE_STRATEGYCENTER_NAME','zh_Hans_CN','发电厂'),
('LOC_DISTRICT_INDUSTRIAL_ZONE_STRATEGYCENTER_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_INDUSTRIAL_ZONE_NAME}，造价更低，建成后为所有城市提供+1[ICON_Power]电力，具有独特的[ICON_Production]生产力相邻加成。[ICON_Production]生产力加成也提供[ICON_Gold]金币。区域拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为1[ICON_Ranged]远程攻击'),
('LOC_UNIT_SPECIAL_KAR98K_NAME','zh_Hans_CN','Kar98k'),
('LOC_UNIT_SPECIAL_KAR98K_DESCRIPTION','zh_Hans_CN','优雅稳重、充满贵族气质的言行，有着极强的荣誉感，命令人的口吻会有种高高在上的威压，但她丰厚熟练的经验与实力，深受所有人敬佩和依赖。'),
('LOC_UNIT_SPECIAL_SVD_NAME','zh_Hans_CN','SVD'),
('LOC_UNIT_SPECIAL_SVD_DESCRIPTION','zh_Hans_CN','轻浮傲慢、自视甚高的人形，喜欢对周遭的事物指手画脚，实际上是个爱操心的老好人。每次有关作战的言论看似嚣张，但在她深不可测的实力和阅历下，最终都会扭转为可能。'),
('LOC_UNIT_SPECIAL_HS50_NAME','zh_Hans_CN','HS.50'),
('LOC_UNIT_SPECIAL_HS50_DESCRIPTION','zh_Hans_CN','由于在原项目的档案已经被抹除，HS.50对自己的过去所知甚少，因此她更加希望能快些融入格里芬。但似乎是因为过去的影响，她只懂得用简单的战术技能来应对日常生活，使得她和同伴们的相处很艰难。目前，HS.50正为变得更加亲和而努力。'),
('LOC_ROMOTION_CLASS_SNIPER_SQUAD_NAME','zh_Hans_CN','远程'),
('LOC_ROMOTION_CLASS_SUPPORT_SQUAD_NAME','zh_Hans_CN','近战支援'),
('LOC_ROMOTION_CLASS_TACTICS_SQUAD_NAME','zh_Hans_CN','近战'),
('LOC_ROMOTION_CLASS_ARMORED_SQUAD_NAME','zh_Hans_CN','重骑兵'),
('LOC_ROMOTION_CLASS_RECON_SQUAD_NAME','zh_Hans_CN','侦查'),
('LOC_ROMOTION_CLASS_ANTITANK_SQUAD_NAME','zh_Hans_CN','攻城反骑兵'),
('LOC_UNIT_NEW_SUPPORT_SQUAD_NAME','zh_Hans_CN','动员支援战术人形小队'),
('LOC_UNIT_NEW_SUPPORT_SQUAD_DESCRIPTION','zh_Hans_CN','临时调动负责后勤的战术人形，进攻时-25[ICON_Strength]战斗力，掠夺只消耗1个[ICON_Movement]移动力。为相邻的战术人形小队+15[ICON_Range]远程战斗力，并增加相邻单位的治疗效果，任意单位从该单位旁开始移动，则+1[ICON_Movement]移动力[NEWLINE][COLOR:ResMilitaryLabelCS]该单位无法获得任何经验[ENDCOLOR]'),
('LOC_UNIT_EXPERIENCED_SUPPORT_SQUAD_NAME','zh_Hans_CN','老练支援战术人形小队'),
('LOC_UNIT_EXPERIENCED_SUPPORT_SQUAD_DESCRIPTION','zh_Hans_CN','仅通过模拟训练或通过使用作战记录提升亦或是某位不吃不喝不给弹药的战术人形(?)用血汗带飞的战术人形，进攻时-25[ICON_Strength]战斗力，掠夺只消耗1个[ICON_Movement]移动力。为相邻的战术人形小队+15[ICON_Range]远程战斗力，并增加相邻单位的治疗效果，任意单位从该单位旁开始移动，则+1[ICON_Movement]移动力'),
('LOC_UNIT_ADVANCED_SUPPORT_SQUAD_NAME','zh_Hans_CN','进阶支援战术人形小队'),
('LOC_UNIT_ADVANCED_SUPPORT_SQUAD_DESCRIPTION','zh_Hans_CN','通过模拟训练，且有一定的实战经验的战术人形，进攻时-25[ICON_Strength]战斗力，掠夺只消耗1个[ICON_Movement]移动力。为相邻的战术人形小队+15[ICON_Range]远程战斗力，并增加相邻单位的治疗效果，任意单位从该单位旁开始移动，则+1[ICON_Movement]移动力'),
('LOC_UNIT_ELITE_SUPPORT_SQUAD_NAME','zh_Hans_CN','精英支援战术人形小队'),
('LOC_UNIT_ELITE_SUPPORT_SQUAD_DESCRIPTION','zh_Hans_CN','装备精良且作战经验丰富的战术人形，进攻时-25[ICON_Strength]战斗力，掠夺只消耗1个[ICON_Movement]移动力。为相邻的战术人形小队+15[ICON_Range]远程战斗力，并增加相邻单位的治疗效果，任意单位从该单位旁开始移动，则+1[ICON_Movement]移动力'),
('LOC_ABILITY_ADD_15_COMBAT_FOR_TACTICS_SQUAD_ALLOW_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','为1格以内的战术人形小队+15[ICON_Range]远程战斗力'),
('LOC_ABILITY_DEBUFF_FOR_SUPPORT_SQUAD_GIRLFONTLINE_GIRLFRONTLINE_DESCRIPTION','zh_Hans_CN','进攻时-25[ICON_Strength]战斗力'),
('LOC_PROMOTION_ADD_15_COMBAT_WHEN_ATTACK_NAME','zh_Hans_CN','潜伏'),
('LOC_PROMOTION_ADD_15_COMBAT_WHEN_ATTACK_DESCRIPTION','zh_Hans_CN','进攻时+15[ICON_Strength]战斗力'),
('LOC_PROMOTION_ADD_7_COMBAT_WHEN_ATTACK_NAME','zh_Hans_CN','钢芯弹'),
('LOC_PROMOTION_ADD_7_COMBAT_WHEN_ATTACK_DESCRIPTION','zh_Hans_CN','进攻时+7[ICON_Strength]战斗力'),
('LOC_PROMOTION_ADD_10_COMBAT_WHEN_ATTACK_NAME','zh_Hans_CN','钨芯弹'),
('LOC_PROMOTION_ADD_10_COMBAT_WHEN_ATTACK_DESCRIPTION','zh_Hans_CN','进攻时+10[ICON_Strength]战斗力'),
('LOC_PROMOTION_ADD_2_SIGHT_ADD_REVEAL_STEALTH_NAME','zh_Hans_CN','热成像仪'),
('LOC_PROMOTION_ADD_2_SIGHT_ADD_REVEAL_STEALTH_DESCRIPTION','zh_Hans_CN','+3视野范围且穿过所有地形地貌，能够发现视野内的隐形单位'),
('LOC_PROMOTION_ADD_15_COMBAT_NAME','zh_Hans_CN','运动战'),
('LOC_PROMOTION_ADD_15_COMBAT_DESCRIPTION','zh_Hans_CN','任何情况下+15[ICON_Strength]战斗力'),
('LOC_PROMOTION_ADD_2_MOVEMENT_NAME','zh_Hans_CN','快速部署'),
('LOC_PROMOTION_ADD_2_MOVEMENT_DESCRIPTION','zh_Hans_CN','+2[ICON_Movement]移动力，编队单位全部获得陪护单位[ICON_Movement]移动力'),
('LOC_PROMOTION_NO_TERRAIN_MOVEMENT_DEBUFF_NAME','zh_Hans_CN','急行军'),
('LOC_UNIT_SPECIAL_FN57_NAME','zh_Hans_CN','FN-57'),
('LOC_UNIT_SPECIAL_FN57_DESCRIPTION','zh_Hans_CN','可爱机灵，有点小自恋的人形，自信的源泉并非实力，而是独到的眼光。平日擅长撒娇和讲笑话，而战斗中即使遭遇失败也能保持冷静不会气馁。'),
('LOC_GIRLFRONTLINE_ADD_15_COMBAT_FOR_TACTICS_SQUAD','zh_Hans_CN','+{1_Amount}[ICON_Strength]远程战斗力，来自相邻支援战术人形'),
('LOC_GIRLFRONTLINE_DEBUFF_FOR_SUPPORT_SQUAD','zh_Hans_CN','{1_Amount}[ICON_Strength]战斗力，来自支援战术人形特性'),
('LOC_ADD_15_COMBAT_WHEN_ATTACK_GIRLFRONTLINE','zh_Hans_CN','+{1_Amount}[ICON_Strength]战斗力，来自{LOC_PROMOTION_ADD_15_COMBAT_WHEN_ATTACK_NAME}'),
('LOC_ADD_7_COMBAT_WHEN_ATTACK_GIRLFRONTLINE','zh_Hans_CN','+{1_Amount}[ICON_Strength]战斗力，来自{LOC_PROMOTION_ADD_7_COMBAT_WHEN_ATTACK_NAME}'),
('LOC_ADD_10_COMBAT_WHEN_ATTACK_GIRLFRONTLINE','zh_Hans_CN','+{1_Amount}[ICON_Strength]战斗力，来自{LOC_PROMOTION_ADD_10_COMBAT_WHEN_ATTACK_NAME}'),
('LOC_ADD_15_COMBAT_GIRLFRONTLINE','zh_Hans_CN','+{1_Amount}[ICON_Strength]战斗力，来自{LOC_PROMOTION_ADD_15_COMBAT_NAME}'),
('LOC_DISTRICT_CAMPUS_FRONTLINECAMP_TYPEONE_NAME','zh_Hans_CN','军械库'),
('LOC_DISTRICT_CAMPUS_FRONTLINECAMP_TYPEONE_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_CAMPUS_NAME}，需要{LOC_TECH_WRITING_NAME}，造价更低，具有独特的[ICON_Gold]金币相邻加成，[ICON_Gold]金币相邻加成也提供[ICON_Science]科研，研究{LOC_TECH_IRON_WORKING_NAME}，[ICON_Gold]金币相邻加成也提供[ICON_Production]生产力。区域拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为1[ICON_Ranged]远程攻击'),
('LOC_DISTRICT_SPACEPORT_FRONTLINECAMP_TYPEONE_NAME','zh_Hans_CN','太空上行链路指挥中心'),
('LOC_DISTRICT_SPACEPORT_FRONTLINECAMP_TYPEONE_DESCRIPTION','zh_Hans_CN','取代{LOC_DISTRICT_SPACEPORT_NAME}，初始解锁，造价免费且永不涨价，可无视人口需求建造（也并非专业化区域），具有独特的[ICON_Production]生产力相邻加成，拥有五个[ICON_Citizen]专家槽，研究{LOC_CIVIC_GUILDS_NAME}，+100%[ICON_Production]生产力相邻加成。区域拥有20点[ICON_Fortified]驻军生命值。城市拥有城墙后，可执行[ICON_Range]范围为1[ICON_Ranged]远程攻击'),
('LOC_TRAIT_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_TYPEONE_NAME','zh_Hans_CN','前线营地'),
('LOC_TRAIT_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_TYPEONE_DESCRIPTION','zh_Hans_CN','城市不会产生厌战情绪，单位无需驻扎在回合开始时恢复生命，城市内所有单元格+4[ICON_Gold]金币，研究{LOC_TECH_ECONOMICS_NAME}后再加+2[ICON_Gold]金币'),
('LOC_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_TYPEONE_DESCRIPTION','zh_Hans_CN','格里芬边境调查团前线营地'),
('LOC_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_TYPEONE_ADJECTIVE','zh_Hans_CN','边境调查团前线营地的'),
('LOC_CIVILIZATION_GIRLFRONTLINE_FRONTLINECAMP_TYPEONE_NAME','zh_Hans_CN','边境调查团-前线营地');
/*
('','zh_Hans_CN',''),
('','zh_Hans_CN',''),
('','zh_Hans_CN',''),
*/